create table pjt_project (
	id varchar(50) not null,
	attachment_id varchar(50),
	comment_subject_id varchar(50),
	created_by_id varchar(50),
	created_by_name varchar(50),
	created_date datetime,
	customer_id varchar(50),
	customer_manager_contact_email varchar(60),
	customer_manager_contact_fax_number varchar(40),
	customer_manager_contact_mobile_phone_number varchar(40),
	customer_manager_contact_name varchar(50),
	customer_manager_contact_telephone_number varchar(40),
	customer_name varchar(50),
	description longtext,
	last_modified_by_id varchar(50),
	last_modified_by_name varchar(50),
	last_modified_date datetime,
	manager_id varchar(50),
	manager_name varchar(50),
	name varchar(50),
	primary key (id)
) engine=InnoDB;
